"""initial schema

Revision ID: f45c1ef96b82
Revises: 
Create Date: 2025-12-24 13:43:06.676024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45c1ef96b82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_no', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_no')
    )
    op.create_table('tenant',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('personal_id', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('line_id', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_id')
    )
    op.create_table('room',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=1), nullable=False),
    sa.Column('size_ping', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_emergency_contact',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electricity_rate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('rate_per_kwh', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('early_termination_date', sa.Date(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_rent_on', sa.SmallInteger(), nullable=False),
    sa.Column('payment_term', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','terminated','expired')", name='check_status'),
    sa.CheckConstraint('pay_rent_on BETWEEN 1 AND 31', name='check_pay_rent_on'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lease_room', 'lease', ['room_id'], unique=False)
    op.create_index('uq_active_lease_per_room', 'lease', ['room_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('meter_reading',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('read_date', sa.Date(), nullable=False),
    sa.Column('read_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meter_room_date', 'meter_reading', ['room_id', 'read_date'], unique=False)
    op.create_index('uq_meter_reading', 'meter_reading', ['room_id', 'read_date'], unique=True)
    op.create_table('lease_asset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lease_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint("asset_type IN ('key', 'fob', 'controller')", name='check_asset_type'),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lease_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('rent','electricity','penalty')", name='check_category'),
    sa.CheckConstraint("status IN ('unpaid','paid','partial','bad_debt')", name='check_status'),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_lease', 'payment', ['lease_id'], unique=False)
    op.create_index('uq_payment_period', 'payment', ['lease_id', 'category', 'period_start', 'period_end'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payment_period', table_name='payment')
    op.drop_index('idx_payment_lease', table_name='payment')
    op.drop_table('payment')
    op.drop_table('lease_asset')
    op.drop_index('uq_meter_reading', table_name='meter_reading')
    op.drop_index('idx_meter_room_date', table_name='meter_reading')
    op.drop_table('meter_reading')
    op.drop_index('uq_active_lease_per_room', table_name='lease', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_lease_room', table_name='lease')
    op.drop_table('lease')
    op.drop_table('electricity_rate')
    op.drop_table('tenant_emergency_contact')
    op.drop_table('room')
    op.drop_table('tenant')
    op.drop_table('building')
    # ### end Alembic commands ###
